### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by inaki** [inaki/moonphases#1]
# Getting Started

This little app pretend to start with the moonphase of today's date and the moonphase of any given date. Best example, discover the moonphase of your date of birth.
### TODOS
- [ ] structure the project and choose some fun framework
- [ ] get a relieble API for getting the moonphases.
- [ ] create a cool date selection input .
- [ ] design the moon either in svg or css.
- [ ] attach moons to the dates from input.
- [ ] code a cool animation showing you the moon of that date.

@ainsleywagon do you wanna play? :waning_crescent_moon: :icecream:
